# Generated by Django 4.1.7 on 2023-03-23 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Words',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=30, verbose_name='Слово')),
                ('piece_word', models.CharField(max_length=30, verbose_name='Часть речи')),
                ('ind_udar', models.IntegerField(verbose_name='Индекс ударной буквы')),
            ],
            options={
                'verbose_name': 'Слово',
                'verbose_name_plural': 'Слова',
            },
        ),
    ]
