# Generated by Django 4.1.7 on 2023-03-23 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='words',
            name='piece_word',
            field=models.CharField(default='', max_length=30, verbose_name='Часть речи'),
        ),
    ]
