# Generated by Django 4.1.7 on 2023-03-23 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_words_piece_word'),
    ]

    operations = [
        migrations.RenameField(
            model_name='words',
            old_name='piece_word',
            new_name='piec_word',
        ),
    ]
