# Generated by Django 4.1.7 on 2023-03-23 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_piece_word_words_piec_word'),
    ]

    operations = [
        migrations.RenameField(
            model_name='words',
            old_name='piec_word',
            new_name='word_2',
        ),
    ]
